#!/bin/bash

B="\e[30m"
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

VALIDATE_1()
{
if [ $1 != 0 ];
then
    $2
    echo -e "${G} $3 ${N}"
fi
}

cd /app

VALIDATE_1 "$?" "mkdir /app" "${G} /app folder created ${N}"